before:
  hooks:
    - go mod download

builds:
  - id: "eru-barrel" 
    binary: eru-barrel
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/projecteru2/barrel/versioninfo.REVISION={{.Commit}}
      - -X github.com/projecteru2/barrel/versioninfo.VERSION={{.Env.VERSION}}
      - -X github.com/projecteru2/barrel/versioninfo.BUILTAT={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
  - id: "eru-barrel-utils"
    main: ./cmd/ctr/ctr.go
    binary: eru-barrel-utils
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/projecteru2/barrel/versioninfo.REVISION={{.Commit}}
      - -X github.com/projecteru2/barrel/versioninfo.VERSION={{.Env.VERSION}}
      - -X github.com/projecteru2/barrel/versioninfo.BUILTAT={{.Date}}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - strip_debug.sh

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
