// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/projecteru2/barrel/service"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Serve provides a mock function with given fields: _a0
func (_m *Service) Serve(_a0 context.Context) (service.Disposable, error) {
	ret := _m.Called(_a0)

	var r0 service.Disposable
	if rf, ok := ret.Get(0).(func(context.Context) service.Disposable); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.Disposable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
