// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/docker/docker/api/types"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// ContainerList provides a mock function with given fields: _a0, _a1
func (_m *Client) ContainerList(_a0 context.Context, _a1 types.ContainerListOptions) ([]types.Container, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []types.Container
	if rf, ok := ret.Get(0).(func(context.Context, types.ContainerListOptions) []types.Container); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Container)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.ContainerListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
