// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/projecteru2/barrel/types"
	mock "github.com/stretchr/testify/mock"
)

// CalicoIPAllocator is an autogenerated mock type for the CalicoIPAllocator type
type CalicoIPAllocator struct {
	mock.Mock
}

// AllocIP provides a mock function with given fields: ctx, ip
func (_m *CalicoIPAllocator) AllocIP(ctx context.Context, ip types.IP) error {
	ret := _m.Called(ctx, ip)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.IP) error); ok {
		r0 = rf(ctx, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AllocIPFromPool provides a mock function with given fields: ctx, poolID
func (_m *CalicoIPAllocator) AllocIPFromPool(ctx context.Context, poolID string) (types.IPAddress, error) {
	ret := _m.Called(ctx, poolID)

	var r0 types.IPAddress
	if rf, ok := ret.Get(0).(func(context.Context, string) types.IPAddress); ok {
		r0 = rf(ctx, poolID)
	} else {
		r0 = ret.Get(0).(types.IPAddress)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poolID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AllocIPFromPools provides a mock function with given fields: ctx, pools
func (_m *CalicoIPAllocator) AllocIPFromPools(ctx context.Context, pools []types.Pool) (types.IPAddress, error) {
	ret := _m.Called(ctx, pools)

	var r0 types.IPAddress
	if rf, ok := ret.Get(0).(func(context.Context, []types.Pool) types.IPAddress); ok {
		r0 = rf(ctx, pools)
	} else {
		r0 = ret.Get(0).(types.IPAddress)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []types.Pool) error); ok {
		r1 = rf(ctx, pools)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDefaultPool provides a mock function with given fields: ipv6
func (_m *CalicoIPAllocator) GetDefaultPool(ipv6 bool) types.Pool {
	ret := _m.Called(ipv6)

	var r0 types.Pool
	if rf, ok := ret.Get(0).(func(bool) types.Pool); ok {
		r0 = rf(ipv6)
	} else {
		r0 = ret.Get(0).(types.Pool)
	}

	return r0
}

// GetPoolByCIDR provides a mock function with given fields: ctx, cidr
func (_m *CalicoIPAllocator) GetPoolByCIDR(ctx context.Context, cidr string) (types.Pool, error) {
	ret := _m.Called(ctx, cidr)

	var r0 types.Pool
	if rf, ok := ret.Get(0).(func(context.Context, string) types.Pool); ok {
		r0 = rf(ctx, cidr)
	} else {
		r0 = ret.Get(0).(types.Pool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cidr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPoolByID provides a mock function with given fields: ctx, poolID
func (_m *CalicoIPAllocator) GetPoolByID(ctx context.Context, poolID string) (types.Pool, error) {
	ret := _m.Called(ctx, poolID)

	var r0 types.Pool
	if rf, ok := ret.Get(0).(func(context.Context, string) types.Pool); ok {
		r0 = rf(ctx, poolID)
	} else {
		r0 = ret.Get(0).(types.Pool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poolID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPoolsByCIDRS provides a mock function with given fields: ctx, cidr
func (_m *CalicoIPAllocator) GetPoolsByCIDRS(ctx context.Context, cidr []string) ([]types.Pool, error) {
	ret := _m.Called(ctx, cidr)

	var r0 []types.Pool
	if rf, ok := ret.Get(0).(func(context.Context, []string) []types.Pool); ok {
		r0 = rf(ctx, cidr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Pool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, cidr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnallocIP provides a mock function with given fields: ctx, ip
func (_m *CalicoIPAllocator) UnallocIP(ctx context.Context, ip types.IP) error {
	ret := _m.Called(ctx, ip)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.IP) error); ok {
		r0 = rf(ctx, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
