// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/projecteru2/barrel/types"
	mock "github.com/stretchr/testify/mock"
)

// DockerNetworkManager is an autogenerated mock type for the DockerNetworkManager type
type DockerNetworkManager struct {
	mock.Mock
}

// GetPoolsByNetworkName provides a mock function with given fields: ctx, name
func (_m *DockerNetworkManager) GetPoolsByNetworkName(ctx context.Context, name string) ([]types.Pool, error) {
	ret := _m.Called(ctx, name)

	var r0 []types.Pool
	if rf, ok := ret.Get(0).(func(context.Context, string) []types.Pool); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Pool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
