// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	io "io"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// SocketInterface is an autogenerated mock type for the SocketInterface type
type SocketInterface struct {
	mock.Mock
}

// RawRequest provides a mock function with given fields: method, url, header, body
func (_m *SocketInterface) RawRequest(method string, url string, header http.Header, body io.Reader) (*http.Response, error) {
	ret := _m.Called(method, url, header, body)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, string, http.Header, io.Reader) *http.Response); ok {
		r0 = rf(method, url, header, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, http.Header, io.Reader) error); ok {
		r1 = rf(method, url, header, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Request provides a mock function with given fields: rawRequest
func (_m *SocketInterface) Request(rawRequest *http.Request) (*http.Response, error) {
	ret := _m.Called(rawRequest)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(rawRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(rawRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
